{% set name = "viser" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/viser-{{ version }}.tar.gz
  sha256: adff0709aa72328eb4beb6a0f33d4622958c8c1b9976fa6ce86c078c1f3d36de

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - viser-build-client = viser._client_autobuild:build_client_entrypoint

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}
    - requests >=2.0.0,<3.0.0
    - websockets >=13.1,<16.0.0
    - numpy >=1.0.0,<3.0.0
    - msgspec >=0.18.6,<1.0.0
    - imageio >=2.0.0,<3.0.0
    - py-opencv >=4.0.0.21,<5.0.0
    - scikit-image >=0.18.0,<1.0.0
    - scipy >=1.7.3,<2.0.0
    - tqdm >=4.0.0,<5.0.0
    - tyro >=0.2.0,<1.0.0
    - rich >=13.3.3,<15.0.0
    - trimesh >=3.21.7,<5.0.0
    - nodeenv >=1.8.0,<2.0.0
    - psutil >=5.9.5,<8.0.0
    - yourdfpy >=0.0.53,<1.0.0

test:
  imports:
    - viser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nerfstudio-project/viser
  summary: Web-based 3D visualization + Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
